FROM python:3.11-slim

ENV DEBIAN_FRONTEND=noninteractive

# Heavy system packages installed ONCE
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-tk \
    xvfb \
    libgl1 \
    libglib2.0-0 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*