apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-showroom-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-showroom-app
  template:
    metadata:
      labels:
        app: car-showroom-app
    spec:
      containers:
      - name: app
        image: abhishaccount/car-showroom-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DISPLAY
          value: ":99"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: car-showroom-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: car-showroom-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30005